{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}
{% set name = data.get('name')|replace("tethysapp-", "")|lower %}

package:
  name: {{ name }}
  version: {{ data.get('version') }}

about:
  author: {{ data.get('author')}}
  description: {{ data.get('description')}}
  license: {{ data.get('license')}}
  dev_url: {{ data.get('url') }}

source:
  path: ..

build:
  noarch: python
  script: python setup.py install --record=record.txt
  preserve_egg_dir: True

requirements:
  build:
    - python

outputs:
  - name: {{ name }}

extra:
  author_email:  {{ data.get('author_email')}}
  keywords: {{ data.get('keywords')}}
  recipe-maintainers:
    - TethysAppWarehouse